[package]
name = "hShip2"
version = "1.0.0"
edition = "2021"

[dependencies]
bevy = { version = "0.7", features = ["mp3", "wav"] }
image = "0.24.5"
rand = "0.8"
winit = "0.26"

[workspace]
resolver = "2"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"
